# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "509d53b887a9a1bc60358b0cca31f696"
application_url = "https://shopify-announcement-app-jfas.onrender.com"
embedded = true
name = "Scaffold the App"

[access_scopes]
scopes = "read_themes"
optional_scopes = []
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://shopify-announcement-app-jfas.onrender.com/api/auth/callback"
]

[webhooks]
api_version = "2026-04"
